### ISSUE TITLE
 MPI_ANY_TYPE might not exist

### ISSUE THREAD

**Issue by shreyashub** [nepda/pi-pp#1]
https://github.com/nepda/pi-pp/blob/9bf9b6958fd530a5d133282d409281901ee4a9d8/serie_4/mpi-master-slave-template.c#L17

I think, instead of MPI_ANY_TYPE, we should use MPI_ANY_TAG.
Is it correct?

**Comment by nepda** [comment]
Thank you for your hint. If I'm honest, this is too long ago to answer your question. But according to the docs and human logic you should be right.
